# [1] AWS Ingress 설정 (기본값: AWS ALB)
ingress:
  className: "alb"

  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip # IP 모드
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/success-codes: "200"  # 헬스 체크 성공 코드
    alb.ingress.kubernetes.io/group.name: spot-ingress

    # HTTPS/HTTP 설정
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-northeast-2:322546275072:certificate/9de3b66e-e361-43f9-bb92-14bc4d677cbf"
#    alb.ingress.kubernetes.io/load-balancer-name: spot-dev-alb # tf위한 이름 고정

# 도메인 (AWS)
domain: spotorder.org

# [2] Deployment 설정
global:
  repository: 322546275072.dkr.ecr.ap-northeast-2.amazonaws.com