apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/first-lounge/Spot.git
    targetRevision: fix/3-monitoring
    path: k8s/overlays/dev/infra
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
