apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/first-lounge/Spot.git
    targetRevision: fix/3-monitoring
    path: k8s/overlays/dev/monitoring/platform
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
