# [1] Ingress 공통 설정 (기본값: AWS ALB)
ingress:
  enabled: true
  className: "alb"

  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip # IP 모드
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/success-codes: "200"  # 헬스 체크 성공 코드
    alb.ingress.kubernetes.io/group.name: spot-ingress

    # HTTPS/HTTP 설정
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-northeast-2:322546275072:certificate/9de3b66e-e361-43f9-bb92-14bc4d677cbf"
#    alb.ingress.kubernetes.io/load-balancer-name: spot-dev-alb # tf위한 이름 고정

  subs:
    - name: www
      namespace: spot
      serviceName: spot-gateway
      healthPath: /actuator/health

    - name: kafka
      namespace: infra
      serviceName: kafka-ui-svc
      healthPath: /

    - name: temporal
      namespace: infra
      serviceName: temporal-ui-svc
      healthPath: /

    - name: grafana
      namespace: monitoring
      serviceName: grafana-service
      healthPath: "/api/health"

# 도메인 (AWS)
domain: spotorder.org

# [2] Deployment 공통 설정 (Global)
global:
  name: spot
  repository: 322546275072.dkr.ecr.ap-northeast-2.amazonaws.com
  imagePullPolicy: Always
  replicas: 1

  # 리소스 제한
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "800m"
    memory: "1Gi"

  # 헬스 체크
  path: /actuator/health

  readiness:
    initial: 90
    period: 10
  liveness:
    initial: 120
    period: 30

# [3] app 목록
apps:
  gateway:
    name: spot-gateway
    port: 80
    targetPort: 8080
    timeoutSeconds: 5
    failureThreshold: 5
    successThreshold: 1

  user:
    name: spot-user
    port: 8081

  store:
    name: spot-store
    port: 8083

  order:
    name: spot-order
    port: 8082

  payment:
    name: spot-payment
    port: 8084

# [4] env
env:
  activeProfile: "k8s"
  loggingConfig: "classpath:logback-spring.xml"
  postgres:
    - db: POSTGRES_DB
      value: "myapp_db"
    - user: POSTGRES_USER
      value: "admin"

# [5] config
config:
  secretName: spot-secrets
  configMapName: spot-app-config