apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - db  # Postgresql & Redis
  - kafka 
  - temporal

  # Monitoring & Logging
  - infra/monitoring/loki/loki.yaml
  - infra/monitoring/loki/loki-config.yaml
  - infra/monitoring/fluent-bit/fluent-bit.yaml
  - infra/monitoring/fluent-bit/fluent-bit-config.yaml

  # Grafana
  - infra/monitoring/grafana/grafana.yaml
  - infra/monitoring/grafana/grafana-config.yaml

  # # Spot Monitoring
  # - infra/monitoring/servicemonitors/spot-gateway-servicemonitor.yaml
  # - infra/monitoring/servicemonitors/spot-user-servicemonitor.yaml
  # - infra/monitoring/servicemonitors/spot-order-servicemonitor.yaml
  # - infra/monitoring/servicemonitors/spot-store-servicemonitor.yaml
  # - infra/monitoring/servicemonitors/spot-payment-servicemonitor.yaml
  # - infra/monitoring/servicemonitors/kafka-broker-podmonitor.yaml
  # - infra/monitoring/servicemonitors/kafka-exporter-servicemonitor.yaml
  # - infra/monitoring/servicemonitors/temporal-servicemonitor.yaml

# ConfigMap으로 여러 config 파일들 생성
configMapGenerator:
  #   - name: spot-app-config
  #     namespace: spot
  #     files:
  #       - config/spot-gateway.yml
  #       - config/common.yml
  #       - config/kafka-topics.yml
  #       - config/spot-user.yml
  #       - config/spot-store.yml
  #       - config/spot-order.yml
  #       - config/spot-payment.yml
  #     options:
  #       disableNameSuffixHash: true

  # - name: kafka-metrics-config
  #   namespace: infra
  #   files:
  #     - infra/monitoring/prometheus/kafka-metrics-config.yaml

  # - name: grafana-dashboards-spot
  #   namespace: monitoring
  #   files:
  #     - infra/monitoring/grafana/dashboards/spot-logs.json

  - name: connector-init
    namespace: infra
    files:
      - infra/kafka/connectors/order-outbox.json
      - infra/kafka/connectors/payment-outbox.json  
      - infra/kafka/connectors/register-connectors.sh

  - name: grafana-dashboards-9578
    namespace: monitoring
    files:
      - infra/monitoring/grafana/dashboards/9578.json

  - name: grafana-dashboards-15661
    namespace: monitoring
    files:
      - infra/monitoring/grafana/dashboards/15661.json

  - name: grafana-dashboards-15757
    namespace: monitoring
    files:
      - infra/monitoring/grafana/dashboards/15757.json

  - name: grafana-dashboards-15760
    namespace: monitoring
    files:
      - infra/monitoring/grafana/dashboards/15760.json

  # - name: grafana-dashboards-kafka-broker
  #   namespace: monitoring
  #   files:
  #     - infra/monitoring/grafana/dashboards/kafka-broker.json

# - name: grafana-dashboards-temporal
#   namespace: monitoring
#   files:
#     - infra/monitoring/grafana/dashboards/temporal.json

# - name: grafana-dashboards-kafka-exporter
#   namespace: monitoring
#   files:
#     - infra/monitoring/grafana/dashboards/kafka-exporter.json

secretGenerator:
  - name: spot-secrets
    namespace: spot
    envs:
      - config/.env
    options:
      disableNameSuffixHash: true

  - name: spot-secrets
    namespace: infra
    envs:
      - config/.env
    options:
      disableNameSuffixHash: true

generatorOptions:
  disableNameSuffixHash: true
