# [1] Local Ingress 설정 (기본값: Ingress-Nginx)
ingress:
  enabled: true
  className: "nginx"

  annotations:
    kubernetes.io/ingress.class: nginx

# 도메인 (local)
domain: localhost

# [2] Deployment 설정
global:
  repository: k3d-spot-registry.localhost:5000
