# [1] AWS Ingress 설정 (기본값: AWS ALB)
ingress:
  className: 'alb'

  aws:
    enabled: true

  # ALB 로그 저장용 S3 버킷 이름
  bucket: null

  subs:
    - name: spot
      hostname: spot
      namespace: spot
      serviceName: spot-gateway
      healthPath: /actuator/health

    - name: kafka
      namespace: infra
      serviceName: kafka-ui-svc
      healthPath: /

    - name: temporal
      namespace: infra
      serviceName: temporal-ui-svc
      healthPath: /

  annotations:
    # ALB 설정
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip # IP 모드

    # 헬스 체크
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/success-codes: '200'

    # 모든 서비스가 하나의 ALB를 공유
    alb.ingress.kubernetes.io/group.name: spot-ingress

    # HTTPS/HTTP 설정
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'

    # 태그 설정
    alb.ingress.kubernetes.io/tags: Name=spot-alb, Environment=dev,Team=spot, ManagedBy=terraform
  
  # subs:
  #   - name: argo
  #     namespace: argocd
  #     groupName: spot-ingress
  #     serviceName: argocd-server
  #     healthPath: /
  #     annotations:
  #       alb.ingress.kubernetes.io/backend-protocol: "HTTPS"
  #       alb.ingress.kubernetes.io/healthcheck-protocol: "HTTPS"

# 도메인 (AWS)
domain: hbksv.cloud

# [2] Deployment 설정
global:
  repository: ""