apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 이 파일이 생성하는 모든 자원을 'infra' 네임스페이스로 강제 지정
namespace: infra

resources:
  - db  # Postgresql & Redis
  - kafka 
  - temporal

generatorOptions:
  disableNameSuffixHash: true

# configMap 파일 생성
configMapGenerator:
  - name: connector-init
    files:
      - kafka/connectors/order-outbox.json
      - kafka/connectors/payment-outbox.json  
      - kafka/connectors/register-connectors.sh

# secret 파일 생성
secretGenerator:
  - name: spot-secrets
    envs:
      - ../config/.env
    options:
      disableNameSuffixHash: true