apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: parameterstore
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef: # IRSA 연결한 ServiceAccount
            name: external-secrets
            namespace: external-secrets
