apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spot-secrets-es
  namespace: spot
spec:
  refreshInterval: 1h
  secretStoreRef: # Secret을 가져올 ClusterSecretStore 작성
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: spot-secrets # k8s에 만들어질 Secret 이름
    creationPolicy: Owner
  data:
    # DB
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: /spot/dev/database/url
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: /spot/dev/database/username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: /spot/dev/database/password
    - secretKey: DB_HOST
      remoteRef:
        key: /spot/dev/database/endpoint

    # Redis
    - secretKey: SPRING_DATA_REDIS_HOST
      remoteRef:
        key: /spot/dev/cache/redis_endpoint

    # JWT
    - secretKey: SPRING_JWT_SECRET
      remoteRef:
        key: /spot/dev/jwt/secret

    # Mail
    - secretKey: EMAIL_USERNAME
      remoteRef:
        key: /spot/dev/mail/username

    - secretKey: EMAIL_PASSWORD
      remoteRef:
        key: /spot/dev/mail/password

    # Toss
    - secretKey: TOSS_SECRET_KEY
      remoteRef:
        key: /spot/dev/toss/secret_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spot-user-secrets-es
  namespace: spot
spec:
  refreshInterval: 1h
  secretStoreRef: # Secret을 가져올 ClusterSecretStore 작성
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: spot-user-secrets # k8s에 만들어질 Secret 이름
    creationPolicy: Owner
  data:
    # DB
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: /spot/dev/database/user/url
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spot-order-secrets-es
  namespace: spot
spec:
  refreshInterval: 1h
  secretStoreRef: # Secret을 가져올 ClusterSecretStore 작성
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: spot-order-secrets # k8s에 만들어질 Secret 이름
    creationPolicy: Owner
  data:
    # DB
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: /spot/dev/database/order/url
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spot-payment-secrets-es
  namespace: spot
spec:
  refreshInterval: 1h
  secretStoreRef: # Secret을 가져올 ClusterSecretStore 작성
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: spot-payment-secrets # k8s에 만들어질 Secret 이름
    creationPolicy: Owner
  data:
    # DB
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: /spot/dev/database/payment/url
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spot-store-secrets-es
  namespace: spot
spec:
  refreshInterval: 1h
  secretStoreRef: # Secret을 가져올 ClusterSecretStore 작성
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: spot-store-secrets # k8s에 만들어질 Secret 이름
    creationPolicy: Owner
  data:
    # DB
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: /spot/dev/database/store/url
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infra-secrets-es
  namespace: infra
spec:
  refreshInterval: 1h
  secretStoreRef: # Secret을 가져올 ClusterSecretStore 작성
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: infra-secrets # k8s에 만들어질 Secret 이름
    creationPolicy: Owner
  data:
    # DB
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: /spot/dev/database/username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: /spot/dev/database/password
    - secretKey: DB_HOST
      remoteRef:
        key: /spot/dev/database/endpoint
