apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-broker
  namespace: monitoring
  labels:
    release: prom
spec:
  namespaceSelector:
    matchNames:
      - infra
  selector:
    matchLabels:
      app: kafka
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
