{
 "title": "K6 Test",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success Rate (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_requests_seconds_count{status=~\"2..\"}[$__rate_interval])) / sum(rate(http_server_requests_seconds_count[$__rate_interval]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"[45]..\"}[5m])) / sum(rate(http_server_requests_seconds_count[5m])) * 100",
     "legendFormat": "{{label_name}}Total"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[5m])) / sum(rate(http_server_requests_seconds_count[5m])) * 100",
     "legendFormat": "{{label_name}}5xx"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"4..\"}[5m])) / sum(rate(http_server_requests_seconds_count[5m])) * 100",
     "legendFormat": "{{label_name}}4xx"
    }
   ]
  },
  {
   "title": "RPS (초당 요청 수)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[$__rate_interval])) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency P95 (응답 속도 95%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "APP Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "JVM Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", service=~\"spot-.*\"}) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Connection Pool (Active)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_active) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU Usage (%) vs Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"spot-.*\", pod!~\"spot-connect.*\", container!=\"\"}) by (pod) \r\n/ sum(kube_pod_container_resource_limits{pod=~\"spot-.*\", pod!~\"spot-connect.*\", resource=\"cpu\"}) by (pod) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Connection Pool (Pending)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_pending) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restart Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{pod=~\"spot-.*\", pod!~\"spot-connect.*\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "K8S (Node & Pods)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Node MEM Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - sum(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) by (instance) / sum(rate(node_cpu_seconds_total[$__rate_interval])) by (instance)) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}