{{- if .Values.env }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers: # 기본 동작은 포어그라운드 삭제
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: default
  sources:
    - repoURL: "https://charts.external-secrets.io"
      chart: external-secrets
      targetRevision: 2.8.0
      helm:
        releaseName: external-secrets
        parameters:
            - name: serviceAccount.name
              value: "external-secrets"
            - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
              value: "arn:aws:iam::164076841262:role/spot-dev-eso-role"
  destination:
    server: {{ .Values.global.destination.server }}
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}