{{- if .Values.env }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-config-app
  namespace: argocd
  finalizers: # 기본 동작은 포어그라운드 삭제
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default
  source:
    path: k8s/overlays/{{ .Values.env }}/external-secrets
    repoURL: {{ .Values.global.repoURL }}
    targetRevision: dev
  destination:
    namespace: argocd
    server: {{ .Values.global.destination.server }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}