apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-prom-app
  namespace: argocd
  finalizers: # 기본 동작은 포어그라운드 삭제
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
    - repoURL: "https://prometheus-community.github.io/helm-charts"
      chart: kube-prometheus-stack
      targetRevision: 56.6.2
      helm:
        releaseName: prom
        valueFiles:
          - $values/k8s/overlays/{{ .Values.env }}/monitoring/platform/prometheus/values.yaml
    - repoURL: {{ .Values.global.repoURL }}
      targetRevision: {{ .Values.global.targetRevision }}
      ref: values
  destination:
    server: {{ .Values.global.destination.server }}
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
