apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollouts-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-rollouts
      targetRevision: 2.41.1
      helm:
        releaseName: argo-rollouts
        parameters:
            # 대시보드 접속 시 인증이 없어 dev에선 X, 필요 시 port-forward
            - name: dashboard.enabled
              value: "false"
  destination:
    server: {{ .Values.global.destination.server }}
    namespace: argo-rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true