apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spot-app
  namespace: argocd
  finalizers: # 기본 동작은 포어그라운드 삭제
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.global.repoURL }}
    targetRevision: {{ .Values.global.targetRevision }}
    path: k8s/spot-apps
    helm:
      releaseName: spot
      valueFiles:
        - values-{{ .Values.env }}.yaml
  destination:
    server: {{ .Values.global.destination.server }}
    namespace: spot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true