apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: kafka-nodes
#  namespace: spot
  namespace: infra
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  replicas: 1 # 3
  template:
    pod:
      affinity: # 특정 노드에 생성되도록 지정
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - ip-10-0-20-53.ap-northeast-2.compute.internal
  roles:
    - broker
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 1Gi
        deleteClaim: true
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m