apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: kafka-nodes
  namespace: infra
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  replicas: 1 # 3

#  # 같은 노드에 kafka가 띄워지지 않게 하는 설정
#  template:
#    pod:
#      affinity:
#        podAntiAffinity:
#          preferredDuringSchedulingIgnoredDuringExecution:
#            - weight: 100
#              podAffinityTerm:
#                labelSelector:
#                  matchLabels:
#                    strimzi.io/cluster: kafka-cluster
#                topologyKey: "kubernetes.io/hostname" # 노드 기준
  roles:
    - broker
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 1Gi
        deleteClaim: true
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
