apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
#  # AWS용
#  storageClassName: gp3
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy
  namespace: monitoring
  labels:
    app: grafana
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext: # PVC 접근 권한을 위한 설정
        runAsUser: 472
        runAsGroup: 472
        fsGroup: 472
      volumes:
        - name: grafana-pv-storage
          persistentVolumeClaim:
            claimName: grafana-pvc

        - name: grafana-config-vol
          configMap:
            name: grafana-config

        - name: dashboards-spot
          configMap:
            name: grafana-dashboards-spot

        - name: prometheus-alertmanager
          configMap:
            name: grafana-dashboards-9578

        - name: dashboards-k8s
          configMap:
            name: dashboards-k8s

        - name: dashboards-infra
          configMap:
            name: dashboards-infra

      containers:
        - name: grafana
          image: grafana/grafana:10.4.3
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Admin"
          envFrom:
            - secretRef:
                name: monitoring-secrets
                optional: true
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "750Mi"

          volumeMounts:
            - name: grafana-pv-storage
              mountPath: /var/lib/grafana

            - name: grafana-config-vol
              mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
              subPath: datasources.yaml
              readOnly: true

            - name: grafana-config-vol
              mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
              subPath: dashboards.yaml
              readOnly: true

            # Spot App Logs
            - name: dashboards-spot
              mountPath: /var/lib/grafana/dashboards/spot-logs.json
              subPath: spot-logs.json
              readOnly: true

            # Prometheus Alertmanager
            - name: prometheus-alertmanager
              mountPath: /var/lib/grafana/dashboards/alertmanager.json
              subPath: alertmanager.json
              readOnly: true

            # K8S Dashboards
            - name: dashboards-k8s
              mountPath: /var/lib/grafana/dashboards/k8s
              readOnly: true

            # Infra Dashboards
            - name: dashboards-infra
              mountPath: /var/lib/grafana/dashboards/infra
              readOnly: true
