apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - servicemonitors/kafka-broker-podmonitor.yaml
  - servicemonitors/kafka-exporter-servicemonitor.yaml
  - servicemonitors/spot-gateway-servicemonitor.yaml
  - servicemonitors/spot-order-servicemonitor.yaml
  - servicemonitors/spot-payment-servicemonitor.yaml
  - servicemonitors/spot-store-servicemonitor.yaml
  - servicemonitors/spot-user-servicemonitor.yaml
  - servicemonitors/temporal-servicemonitor.yaml

configMapGenerator:
  - name: kafka-metrics-config
    namespace: infra
    files:
      - prometheus/kafka-metrics-config.yaml
