apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Grafana
  - grafana.yaml
  - grafana-config.yaml

generatorOptions:
  disableNameSuffixHash: true

# ConfigMap으로 config 파일들 생성
configMapGenerator:
  - name: grafana-dashboards-spot
    files:
      - dashboards/spot-logs.json

  - name: grafana-dashboards-9578
    files:
      - dashboards/9578.json

  - name: grafana-dashboards-15661
    files:
      - dashboards/15661.json

  - name: grafana-dashboards-15757
    files:
      - dashboards/15757.json

  - name: grafana-dashboards-15760
    files:
      - dashboards/15760.json

  - name: grafana-dashboards-kafka-broker
    files:
      - dashboards/kafka-broker.json

  - name: grafana-dashboards-temporal
    files:
      - dashboards/temporal.json

  - name: grafana-dashboards-kafka-exporter
    files:
      - dashboards/kafka-exporter.json
