apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml

# .env를 네임스페이스별 Secret 매니페스트 생성
secretGenerator:
  - name: spot-secrets
    namespace: spot
    envs:
      - .env

  - name: infra-secrets
    namespace: infra
    envs:
      - .env
