apiVersion: batch/v1
kind: Job
metadata:
  name: connector-register
  namespace: infra
spec:
  ttlSecondsAfterFinished: 60 # job 완료 후 60초 후에 자동으로 삭제
  template:
    spec:
      containers:
      - name: connector-register
        image: curlimages/curl:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: spot-secrets
        command: ["/bin/sh", "-c", "sh /configs/register-connectors.sh"]
        volumeMounts:
        - name: connector-configs
          mountPath: /configs
      volumes:
      - name: connector-configs
        configMap:
          name: connector-init
      restartPolicy: Never
