{{- range $key, $val := .Values.apps }}
{{- if not $val.rollout }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $val.name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $val.name }}
spec:
  replicas: {{ $.Values.global.replicas | default 1}}
  selector:
    matchLabels:
      app: {{ $val.name }}
  template:
    metadata:
      labels:
        app: {{ $val.name }}
    spec:
      containers:
        - name: {{ $val.name }}
          image: "{{ $.Values.global.repository }}/{{ $val.name }}:{{ $val.imageTag }}"
          imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ $val.targetPort | default $val.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ $.Values.env.activeProfile }}
            - name: LOGGING_CONFIG
              value: {{ $.Values.env.loggingConfig }}
            {{- if and $.Values.environment ($val.dbEnabled) }}
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: spot-{{ $key }}-secrets
                  key: SPRING_DATASOURCE_URL
            {{- end }}

            # 어플리케이션 환경 변수
          envFrom:
            - secretRef:
                name: {{ $.Values.envFrom.secretName}}
            - configMapRef:
                name: {{ $.Values.envFrom.configName }}

          # 리소스 설정
          resources:
            requests:
              cpu: {{ $.Values.global.requests.cpu }}
              memory: {{ $.Values.global.requests.memory}}
            limits:
              cpu: {{ $.Values.global.limits.cpu }}
              memory: {{ $.Values.global.limits.memory }}

          # Startup
          startupProbe:
            httpGet:
              path: {{ $.Values.probes.path }}{{ required "probes.startup.path 필요" $.Values.probes.startup.path }}
              port: {{ $val.targetPort | default $val.port }}
            periodSeconds: {{ $.Values.probes.startup.period }}
            failureThreshold: {{ $.Values.probes.startup.failureThreshold }}
            timeoutSeconds: {{ $.Values.probes.timeoutSeconds }}

          # Readiness
          readinessProbe:
            httpGet:
              path: {{ $.Values.probes.path }}{{ $.Values.probes.readiness.path }}
              port: {{ $val.targetPort | default $val.port }}
            periodSeconds: {{ $.Values.probes.readiness.period }}
            failureThreshold: {{ $.Values.probes.readiness.failureThreshold }}
            timeoutSeconds: {{ $.Values.probes.timeoutSeconds }}

          # Liveness
          livenessProbe:
            httpGet:
              path: {{ $.Values.probes.path }}{{ $.Values.probes.liveness.path }}
              port: {{ $val.targetPort | default $val.port }}
            periodSeconds: {{ $.Values.probes.liveness.period }}
            failureThreshold: {{ $.Values.probes.liveness.failureThreshold }}
            timeoutSeconds: {{ $.Values.probes.timeoutSeconds }}

          # 볼륨 마운트
          volumeMounts:
            - name: app-config
              mountPath: /config
              readOnly: true

      volumes:
        - name: app-config
          configMap:
            name: {{ $.Values.configMap }}
{{- end }}
{{- end }}