{{- range $key, $sub := .Values.ingress.subs }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $key }}-ing
  namespace: {{ $sub.namespace }}
  annotations:
  {{- if $.Values.ingress.aws.enabled }}
    alb.ingress.kubernetes.io/load-balancer-attributes: "access_logs.s3.enabled=true,access_logs.s3.bucket={{ $.Values.ingress.bucket }},access_logs.s3.prefix=alb"
    alb.ingress.kubernetes.io/healthcheck-path: {{ $sub.healthPath | default "/" | quote }}
  {{- range $k, $value := $.Values.ingress.annotations }}
    {{- /* annotations의 각 key의 value가 존재하는 경우 */ -}}
    {{- if $value }}
    {{ $k }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- else }}
    kubernetes.io/ingress.class: nginx
  {{- end }}

spec:
  ingressClassName: {{ $.Values.ingress.className }}
  rules:
    - host: {{ $sub.hostname | default $key }}.{{ $.Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $sub.serviceName }}
                port:
                  number: {{ $sub.servicePort | default 80 }}
{{- end}}