{{- range $key, $val := .Values.apps }}
{{- if $val.rollout }}
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ $val.name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $val.name }}
spec:
  replicas: {{ $.Values.global.replicas }}
  selector:
    matchLabels:
      app: {{ $val.name }}
  template:
    metadata:
      labels:
        app: {{ $val.name }}
    spec:
      containers:
        - name: {{ $val.name }}
          image: "{{ $.Values.global.repository }}/{{ $val.name }}:{{ $val.imageTag }}"
          imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ $val.targetPort | default $val.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ $.Values.env.activeProfile }}
            - name: LOGGING_CONFIG
              value: {{ $.Values.env.loggingConfig }}
            {{- if and $.Values.environment ($val.dbEnabled) }}
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: spot-{{ $key }}-secrets
                  key: SPRING_DATASOURCE_URL
            {{- end }}

          # 어플리케이션 환경 변수
          envFrom:
            - secretRef:
                name: {{ $.Values.envFrom.secretName}}
            - configMapRef:
                name: {{ $.Values.envFrom.configName }}

          # 리소스 설정
          resources:
            requests:
              cpu: {{ $.Values.global.requests.cpu }}
              memory: {{ $.Values.global.requests.memory}}
            limits:
              cpu: {{ $.Values.global.limits.cpu }}
              memory: {{ $.Values.global.limits.memory }}

          # Startup
          startupProbe:
            httpGet:
              path: {{ $.Values.global.path }}
              port: {{ $val.targetPort | default $val.port }}
            periodSeconds: {{ $.Values.global.startup.period }}
            failureThreshold: {{ $.Values.global.startup.failureThreshold }}
            timeoutSeconds: {{ $.Values.global.timeoutSeconds }}

          # Readiness
          readinessProbe:
            httpGet:
              path: {{ $.Values.global.path }}
              port: {{ $val.targetPort | default $val.port }}
            periodSeconds: {{ $.Values.global.readiness.period }}
            failureThreshold: {{ $.Values.global.readiness.failureThreshold }}
            timeoutSeconds: {{ $.Values.global.timeoutSeconds }}

          # Liveness
          livenessProbe:
            httpGet:
              path: {{ $.Values.global.path }}
              port: {{ $val.targetPort | default $val.port }}
            periodSeconds: {{ $.Values.global.liveness.period }}
            failureThreshold: {{ $.Values.global.liveness.failureThreshold }}
            timeoutSeconds: {{ $.Values.global.timeoutSeconds }}

          # 볼륨 마운트
          volumeMounts:
            - name: app-config
              mountPath: /config
              readOnly: true
      volumes:
        - name: app-config
          configMap:
            name: {{ $.Values.configMap }}
  strategy:
    blueGreen:
      autoPromotionEnabled: {{ $val.autoPromotionEnabled }}
      activeService: {{ $val.name }}
      previewService: {{ $val.name }}-preview
      scaleDownDelaySeconds: {{ $val.scaleDownDelaySeconds }}
      prePromotionAnalysis:
        templates:
          - templateName: {{ $val.name }}-smoke-test
{{- end }}
{{- end }}